export const defaultConferenceConfig = {
  brand: "",
  brandInitials: "",
  shortName: "",
  tagline: "",
  name: "",
  primaryColor: "#0d7e52",
  themeColor: "",
  logoUrl: "",
  streamUrl: "",
  dates: "",
  location: "",
  description: "",
  schedule: [],
};
