export const adminConfig = {
  brandTitle: "Conference Admin Panel",
  conferenceName: "",
  conferenceLogo: "",
  themeColor: "#0d7e52",
  brandAcronym: "",
  welcomeMessage: "",
  navItems: [
    { path: "/app/dashboard", label: "Dashboard" },
    { path: "/app/events", label: "Events" },
    { path: "/app/program", label: "Program" },
    { path: "/app/users", label: "Users" },
    { path: "/app/presentations", label: "Presentations" },
    { path: "/app/streams", label: "Streams" },
    { path: "/app/keynote-in-app", label: "Keynotes" },
    { path: "/app/sponsors", label: "Sponsors" },
    { path: "/app/discovery-card", label: "Discovery Card" },
    { path: "/app/database", label: "Database" },
    { path: "/app/export", label: "Export Data" },
    { path: "/app/settings", label: "Settings" },
  ],
};
