name: elmoultaqa_mobile
description: A Flutter mobile scaffold for ElMoultaqa.
publish_to: "none"
version: 0.1.0+1
environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  url_launcher: ^6.1.0
  shared_preferences: ^2.2.0
  image_picker: ^1.0.0
  webview_flutter: ^4.10.0
  flutter_dotenv: ^6.0.1
  flutter_secure_storage: ^11.1.1
  supabase_flutter: ^2.8.3
  clerk_flutter: ^0.0.16-beta
  clerk_auth: ^0.0.16-beta
  app_links: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/logo.png
    - assets/icons/icon.png
